import { User } from '@/types';

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'john.doe@company.com',
    firstName: 'John',
    lastName: 'Doe',
    role: 'employee',
    employeeId: 'EMP001',
    avatar: '',
    department: 'Engineering',
    designation: 'Software Engineer',
    managerId: '2',
    location: 'San Francisco',
    isOnboarded: true,
    createdAt: '2023-01-15T00:00:00Z',
  },
  {
    id: '2',
    email: 'jane.smith@company.com',
    firstName: 'Jane',
    lastName: 'Smith',
    role: 'hr',
    employeeId: 'EMP002',
    avatar: '',
    department: 'Human Resources',
    designation: 'HR Manager',
    managerId: '5',
    location: 'San Francisco',
    isOnboarded: true,
    createdAt: '2022-05-10T00:00:00Z',
  },
  {
    id: '3',
    email: 'admin@company.com',
    firstName: 'Admin',
    lastName: 'User',
    role: 'admin',
    employeeId: 'EMP003',
    avatar: '',
    department: 'IT',
    designation: 'System Administrator',
    managerId: null,
    location: 'Remote',
    isOnboarded: true,
    createdAt: '2022-01-01T00:00:00Z',
  },
  {
    id: '4',
    email: 'mike.johnson@company.com',
    firstName: 'Mike',
    lastName: 'Johnson',
    role: 'employee',
    employeeId: 'EMP004',
    avatar: '',
    department: 'Engineering',
    designation: 'Senior Software Engineer',
    managerId: '2',
    location: 'New York',
    isOnboarded: true,
    createdAt: '2022-08-20T00:00:00Z',
  },
  {
    id: '5',
    email: 'sarah.williams@company.com',
    firstName: 'Sarah',
    lastName: 'Williams',
    role: 'hr',
    employeeId: 'EMP005',
    avatar: '',
    department: 'Human Resources',
    designation: 'HR Director',
    managerId: '3',
    location: 'San Francisco',
    isOnboarded: true,
    createdAt: '2021-03-15T00:00:00Z',
  },
];

export const mockCredentials: Record<string, { password: string }> = {
  'john.doe@company.com': { password: 'password123' },
  'jane.smith@company.com': { password: 'password123' },
  'admin@company.com': { password: 'admin123' },
  'mike.johnson@company.com': { password: 'password123' },
  'sarah.williams@company.com': { password: 'password123' },
};
