import { Employee } from '@/types';

export const mockEmployees: Employee[] = [
  {
    id: '1',
    email: 'john.doe@company.com',
    firstName: 'John',
    lastName: 'Doe',
    role: 'employee',
    employeeId: 'EMP001',
    department: 'Engineering',
    designation: 'Software Engineer',
    managerId: '2',
    location: 'San Francisco',
    isOnboarded: true,
    createdAt: '2023-01-15T00:00:00Z',
    personalDetails: {
      dateOfBirth: '1990-05-15',
      gender: 'male',
      maritalStatus: 'single',
      bloodGroup: 'O+',
      nationality: 'US',
      languages: ['English', 'Spanish'],
    },
    contactDetails: {
      phone: '+1-555-0101',
      alternatePhone: '+1-555-0102',
      personalEmail: 'john.doe@gmail.com',
      address: {
        street: '123 Main St',
        city: 'San Francisco',
        state: 'CA',
        zipCode: '94105',
        country: 'USA',
      },
    },
    emergencyContacts: [
      {
        name: 'Jane Doe',
        relationship: 'Spouse',
        phone: '+1-555-0103',
      },
    ],
    jobDetails: {
      employeeId: 'EMP001',
      designation: 'Software Engineer',
      department: 'Engineering',
      location: 'San Francisco',
      reportingTo: 'Jane Smith',
      dateOfJoining: '2023-01-15',
      employmentType: 'full-time',
      workMode: 'hybrid',
    },
    bankDetails: {
      bankName: 'Chase Bank',
      accountNumber: '****1234',
      ifscCode: 'CHASUS33',
      accountType: 'savings',
    },
    documents: [],
  },
  {
    id: '2',
    email: 'jane.smith@company.com',
    firstName: 'Jane',
    lastName: 'Smith',
    role: 'hr',
    employeeId: 'EMP002',
    department: 'Human Resources',
    designation: 'HR Manager',
    managerId: '5',
    location: 'San Francisco',
    isOnboarded: true,
    createdAt: '2022-05-10T00:00:00Z',
    personalDetails: {
      dateOfBirth: '1985-08-22',
      gender: 'female',
      maritalStatus: 'married',
      bloodGroup: 'A+',
      nationality: 'US',
      languages: ['English', 'French'],
    },
    contactDetails: {
      phone: '+1-555-0201',
      alternatePhone: '+1-555-0202',
      personalEmail: 'jane.smith@gmail.com',
      address: {
        street: '456 Oak Ave',
        city: 'San Francisco',
        state: 'CA',
        zipCode: '94102',
        country: 'USA',
      },
    },
    emergencyContacts: [
      {
        name: 'Robert Smith',
        relationship: 'Spouse',
        phone: '+1-555-0203',
      },
    ],
    jobDetails: {
      employeeId: 'EMP002',
      designation: 'HR Manager',
      department: 'Human Resources',
      location: 'San Francisco',
      reportingTo: 'Sarah Williams',
      dateOfJoining: '2022-05-10',
      employmentType: 'full-time',
      workMode: 'onsite',
    },
    bankDetails: {
      bankName: 'Bank of America',
      accountNumber: '****5678',
      ifscCode: 'BOFAUS3N',
      accountType: 'savings',
    },
    documents: [],
  },
];
